
# Database
spring:
  datasource:
    url: jdbc:oracle:thin:@PY6XL5CJWQ1ZMSW9_medium?TNS_ADMIN=/Users/yujehwan/Downloads/Wallet_PY6XL5CJWQ1ZMSW9
    username: Admin
    password: Message70992

  # JPA
  jpa:
    database: Oracle
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show-sql: true # System.out? ?? ???.
        format_sql: true
        jdbc.lob.non_contextual_creation: true

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace # ???? ????.

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  header: Authorization
  secret: dlrjssorkwwpdlfdjfudnjgksmsjwtdlswmdxhzmsqkdtlrdleksorkdlrjfrhdqnfmfgksmsepsjandjfudnsrjrkxek
  token-validity-in-seconds: 86400
